name: Test

on: [push]

jobs:
  test-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Install Neko
      run: |
        wget https://github.com/HaxeFoundation/neko/releases/download/v${NEKO_VERSION//./-}/neko-${NEKO_VERSION}-linux64.tar.gz
        tar xzvf neko-${NEKO_VERSION}-linux64.tar.gz
        rm neko-${NEKO_VERSION}-linux64.tar.gz
        mv neko-${NEKO_VERSION}-linux64 $HOME/neko
        echo "$HOME/neko" >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/neko" >> $GITHUB_ENV
      env:
        NEKO_VERSION: 2.3.0
    - name: Install Haxe
      run: |
        wget https://github.com/HaxeFoundation/haxe/releases/download/${HAXE_VERSION}/haxe-${HAXE_VERSION}-linux64.tar.gz
        mkdir haxe && tar xzvf haxe-${HAXE_VERSION}-linux64.tar.gz -C haxe --strip-components 1
        rm haxe-${HAXE_VERSION}-linux64.tar.gz
        mv haxe $HOME/haxe
        echo "$HOME/haxe" >> $GITHUB_PATH
        echo "HAXE_STD_PATH=$HOME/haxe/std" >> $GITHUB_ENV
      env:
        HAXE_VERSION: 4.1.5
    - uses: actions/checkout@v2
    - name: Install Haxelib
      run: |
        mkdir $HOME/haxelib && haxelib setup $HOME/haxelib
        haxelib install buddy
        haxelib install utest
        haxelib install hxnodejs
        haxelib install hxcpp
        haxelib install hxjava
    - name: Run test - JS
      run: haxe test-js.hxml
    - name: Run test - eval
      run: haxe test-eval.hxml
    - name: Run test - Neko
      run: haxe test-neko.hxml
    - name: Run test - C++
      run: haxe test-cpp.hxml
    - name: Run test - Java
      run: haxe test-java.hxml
    - name: Run test - jvm
      run: haxe test-jvm.hxml
