name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Neko
      run: |
        wget https://github.com/HaxeFoundation/neko/releases/download/v${NEKO_VERSION//./-}/neko-${NEKO_VERSION}-linux64.tar.gz
        tar xzf neko-${NEKO_VERSION}-linux64.tar.gz
        rm neko-${NEKO_VERSION}-linux64.tar.gz
        mv neko-${NEKO_VERSION}-linux64 $HOME/neko
        echo "::add-path::$HOME/neko"
      env:
        NEKO_VERSION: 2.3.0
    - name: Install Haxe
      run: |
        wget https://github.com/HaxeFoundation/haxe/releases/download/${HAXE_VERSION}/haxe-${HAXE_VERSION}-linux64.tar.gz
        tar xzf haxe-${HAXE_VERSION}-linux64.tar.gz
        rm haxe-${HAXE_VERSION}-linux64.tar.gz
        mv haxe-${HAXE_VERSION}-linux64 $HOME/haxe
        echo "::add-path::$HOME/haxe"
      env:
        HAXE_VERSION: 4.0.5
