name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install Neko
      run: |
        wget https://github.com/HaxeFoundation/neko/releases/download/v${NEKO_VERSION//./-}/neko-${NEKO_VERSION}-linux64.tar.gz
        tar xzvf neko-${NEKO_VERSION}-linux64.tar.gz
        rm neko-${NEKO_VERSION}-linux64.tar.gz
        mv neko-${NEKO_VERSION}-linux64 $HOME/neko
        echo "::add-path::$HOME/neko"
        echo "::set-env name=LD_LIBRARY_PATH::$LD_LIBRARY_PATH:$HOME/neko"
      env:
        NEKO_VERSION: 2.3.0
    - name: Install Haxe
      run: |
        wget https://github.com/HaxeFoundation/haxe/releases/download/${HAXE_VERSION}/haxe-${HAXE_VERSION}-linux64.tar.gz
        mkdir haxe && tar xzvf haxe-${HAXE_VERSION}-linux64.tar.gz -C haxe --strip-components 1
        rm haxe-${HAXE_VERSION}-linux64.tar.gz
        mv haxe $HOME/haxe
        echo "::add-path::$HOME/haxe"
        echo "::set-env name=HAXE_STD_PATH::$HOME/haxe/std"
      env:
        HAXE_VERSION: 4.0.5
    - name: Install Haxelib
      run: |
        mkdir $HOME/haxelib && haxelib setup $HOME/haxelib
        haxelib install buddy
    - uses: actions/checkout@v2
    - name: Run test - Neko
      run: haxe test-neko.hxml
    
